### ISSUE TITLE
Gallery images with a very high vertical resolution aren't in focus unless fullscreened.

### ISSUE THREAD

**Issue by Cormak** [Kennyc1012/OpenImgur#56]
Here's an example. Not focused (or possibly thumbnailed and stretched) when in initial gallery view. Properly displayed when tapped to view image in fullscreen though.

https://imgur.com/gallery/b5cgSCe

Seeing this problem on my Nexus 5. No other phone or tablet to test on.

**Comment by Kennyc1012** [comment]
This is an issue with Android itself. The maximum width/height an image can be is 2048px by 2048px (Opengl limitation). Due to this limitation, any image that is larger than this will load a scaled down version resulting in a blurry photo. It will look correctly when viewed full screen because it is only loading and displaying the section of the photo that you are currently zoomed in on.
